<a href="https://colab.research.google.com/github/giorgiagandolfi/laboratory_of_bioinformatics1/blob/master/prova_lezione.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
names[:-1]

In [0]:
import pandas as pd

url = 'https://raw.githubusercontent.com/dbonacorsi/AML_basic_AA1920/master/datasets/pima-indians-diabetes.data.csv'

names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names=names)
data

# Rescale data:


In [0]:
from numpy import set_printoptions

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
array = data.values
array

In [0]:
type(array)

In [0]:
X = array[:, 0:8] # all the possible row with all columnbs
Y = array [:, 8]

In [0]:
X #features

In [0]:
Y #is the last column with the class

In [0]:
#resclaled data in a specifi range, in this case 0-1 or 0-10
scaler_1 = MinMaxScaler(feature_range=(0, 1)) 
scaler_2 = MinMaxScaler(feature_range=(0, 10))
rescaledX_1 = scaler_1.fit_transform(X) #prepare and run the transform
rescaledX_2 = scaler_2.fit_transform(X)

#summarize
set_printoptions(precision=3)
#print(X[0:5,:])

print(rescaledX_1[0:5,:]) # rescaling


In [0]:
print(rescaledX_2[0:5, :])

# Standardize data

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
# mean = 0 and stdev = 1
scaler_1 = StandardScaler().fit(X)
rescaledX_1 = scaler_1.transform(X)

In [22]:
# summarize transform data
set_printoptions(precision=3)
print(rescaledX_1[0:5, :])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


# Normalize data: 
I want a lenght of one. This method is useful when I have sparse data. Different ways. 

In [0]:
from sklearn.preprocessing import Normalizer

# Binarize data:
It is not mandatory to be applied. Idea: take the data and **trasform them either in 0 or 1** depending on a threshold. Libraries to this for us. 

# Feature selection

Understand among the attrbutes, how to selelect the best features. 

1) **reduction of overfitting**: the features are there because they are expressive and from which I can leran somehting;

2) **improvement of the accurancy**: if we don't have misleading data in the sample, the modle accurnacy can be improved. Get a model that is more accurate,a ble to better generalize

3) **reduction of training time.**


In [0]:
import pandas as pd

url = 'https://raw.githubusercontent.com/dbonacorsi/AML_basic_AA1920/master/datasets/pima-indians-diabetes.data.csv'

names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names=names)
data

# Univariate selection

In [0]:
#from pandas import read_csv
from numpy import set_printoptions

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [0]:
array = data.values
X = array[:, 0:8]
Y = array[:,8]

In [0]:
X.shape #features

In [0]:
Y.shape #labels

Usare il test del chi2 per trovare la migliore feature (k) tra le 8 possibili.

In [0]:
test = SelectKBest(score_func=chi2, k=3)
fit = test.fit(X, Y)

Summarize the scores retrieved from the test

In [57]:
set_printoptions(precision=3)
print(fit.scores_)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [39]:
names[:-1]

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age']

As it is possible to see, the best features are the ones with the highestvalue of chi2: **plas, test and age**.

In [0]:
X_new = SelectKBest(score_func=chi2, k=3).fit_transform(X, Y)

In [41]:
X_new.shape

(768, 3)

In [0]:
X_new

In the next step we can summurize the best selected features

In [0]:
X_new1 = fit.transform(X)
print(X_new1[0:10,:])

We can do this also in one single shot (even if dangerous)

In [0]:
X_new2 = SelectKBest(score_func=chi2, k=3).fit_transform(X,Y)
print(X_new2[0:10,:])

# Recursive Feature Elimination


In [0]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [0]:
model = LogisticRegression()
rfe = RFE(model, 3)
fit = rfe.fit(X, Y)
print("Num. Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking:%s" % fit.ranking_)

In [0]:
names[:-1]

In this case the top 3 features selected are: **preg,mass and pedi**.

# Feature Importance

In [0]:
from sklearn.ensemble import ExtraTreesClassifier

In [0]:
model = ExtraTreesClassifier()
model.fit(X, Y)
print(model.feature_importances_)

In [0]:
names[:-1]

The largest the score, the more important the feature associated to: in this case the three most important features are **preg, plas and age**.

# PCA

In [0]:
from sklearn.decomposition import PCA

In [0]:
pca = PCA(n_components=3)
fit = pca.fit(X)
print("Explained Variance: %s" % fit.explained_variance_ratio_)

# Result exercise:
 1. plas, test and age
 2. preg, mass and pedi
 3. plas, mass and age

 plas = 2
 
 test = 1
 
 age = 2
 
 pedi = 1
 
 mass = 2 

 **plas, age and mass**

# Evaluate the perfomrance of ML algo with **Resampling**

## 1. Split into Train and Test Sets

## 2. K-fold Cross-Validation